name: games
description: A framework and application for simulating games.
version: 1.0.0
homepage: https://github.com/glesica/games.dart
authors:
  - George Lesica <george@lesica.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  meta: ^1.0.0

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0

